### ISSUE TITLE
java.io.EOFException

### ISSUE THREAD

**Issue by ofry** [artspb/idea-php-latest-plugin#5]
IntelliJ IDEA 2018.3 (Ultimate Edition)
Build #IU-183.4284.148, built on November 21, 2018

JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Ubuntu 18.10 x64

PHP latest v0.4

```
java.io.EOFException
	at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.read(GzipCompressorInputStream.java:278)
	at java.io.InputStream.read(InputStream.java:101)
	at org.rauschig.jarchivelib.IOUtils.copy(IOUtils.java:82)
	at org.rauschig.jarchivelib.IOUtils.copy(IOUtils.java:66)
	at org.rauschig.jarchivelib.CommonsCompressor.decompress(CommonsCompressor.java:88)
	at org.rauschig.jarchivelib.ArchiverCompressorDecorator.extract(ArchiverCompressorDecorator.java:73)
	at me.artspb.idea.php.latest.plugin.PhpLocalInterpreterUpdater$downloadInterpreter$1.run(PhpLocalInterpreterUpdater.kt:112)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by artspb** [comment]
@ofry Unfortunately, I cannot reproduce this problem. It could be that an archive was improperly downloaded. Could you please try removing `~/.IntelliJIdea2018.3/system/caches/plugins/idea-php-latest-plugin/`, then opening any project. The archive should be re-downloaded.

**Comment by ofry** [comment]
Then I have feature request:

If an archive was improperly downloaded, then plugin should automatically try to re-download.

**Comment by artspb** [comment]
Sounds valid to me. Still, I'm wondering whether the trick with removing a file helped.
