### ISSUE TITLE
java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by webuxr** [artspb/idea-php-latest-plugin#6]
I received the following *SocketTimeoutException* stack trace after opening PhpStorm 2018.3.2 this morning. I'm running v0.4 of the **PHP Latest** plug-in.

My setup:
PhpStorm 2018.3.2
Build #PS-183.4886.46, built on December 19, 2018
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

`java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:609)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:378)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:387)
	at me.artspb.idea.php.latest.plugin.GitHubClientKt$requestRelease$2.process(GitHubClient.kt:32)
	at me.artspb.idea.php.latest.plugin.GitHubClientKt$requestRelease$2.process(GitHubClient.kt)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:352)
	at me.artspb.idea.php.latest.plugin.GitHubClientKt.requestRelease(GitHubClient.kt:31)
	at me.artspb.idea.php.latest.plugin.PhpLocalInterpreterUpdater$requestRelease$1.run(PhpLocalInterpreterUpdater.kt:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by artspb** [comment]
Fixed in master.

**Comment by webuxr** [comment]
@artspb: Wonderful! I’ll test later on today and will re-open IF needed. Thank you for the rapid response!

**Comment by artspb** [comment]
@webuxr First of all, I didn't update the plugin in the repository so there's nothing to test yet. Secondly, the only thing I did is an error suppression so it's only written to a log instead of popping up. The real cause of your problem is network connectivity. If it appears again you should check that you can download [this file](https://github.com/artspb/php-latest-mac/releases/download/v7.2.12/php72-v7.2.12.tar.gz) for instance via your browser. If it works fine, you can close a project and then open it again for the interpreter to be re-downloaded. Please let me know if the issue persists when you've done all the steps above. Thanks.
